// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekkhzqcjpxzzjtzoojry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVra2h6cWNqcHh6emp0em9vanJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MzY0NTYsImV4cCI6MjA2NTExMjQ1Nn0.gLadeqAZTZmlcHc7VJeCcuwh5aGKT462nDOaTLJr7do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);